name: App CI

on:
  push:
    # Run on all branches
    branches:
      - "**"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"
  pull_request:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"

jobs:

  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: 🏗 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: 🗂️ Install dependencies
        run: npm i

      - name: 🔨 Build
        run: npm run build:ci

      - name: 🧪 Test
        run: npm run test:ci

      # Upload dist artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      # Upload coverage artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  coverage:
    name: Coverage Analysis
    if: github.ref != 'refs/heads/feature/ftp-deploy'
    needs: buildAndTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Download coverage artifacts
      - uses: actions/download-artifact@v5
        with:
          name: coverage

      - name: 📈 Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deployFTP:
    name: Deploy to FTP
    # Deploy only for test branch
    if: github.ref == 'refs/heads/feature/ftp-deploy'
    needs: buildAndTest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: prod
      url: https://dcpesses.github.io/portfolio-redux/ # <- Change to your site url
    steps:
      # Download dist artifacts
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist/

      - name: Set current date as env variable
        run: echo "NOW=$(TZ=America/Los_Angeles date +'%F %T %Z')" >> $GITHUB_ENV

      # - name: Debug current date
      #   run: echo "${{ env.NOW }}" # Gives "2024-02-16 16:53:32 PST" modifiedFiles

      - name: Find and Replace
        id: find_replace_datetime
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "DATE_TIME"
          replace: "${{ env.NOW }}"
          regex: false
          include: "**index.html"

      # - name: 🚀 Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4.0.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: dist

      - name: Find and Replace Basename
        id: find_replace_basename1
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "/portfolio-redux"
          replace: ""
          regex: false
          include: "**/**index**.!(map)"

      - name: Find and Replace Basename
        id: find_replace_basename2
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "/portfolio-redux"
          replace: ""
          regex: false
          include: "**/**index**.(html|js|css)"

      - name: Find and Replace Basename
        id: find_replace_basename3
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "/portfolio-redux"
          replace: ""
          regex: false
          include: "**/**index**.*(html|js|css)"


      - name: Modified Files
        run:
          echo "find_replace_datetime:"
          echo "${{ steps.find_replace_datetime.outputs.modifiedFiles }}\n"
          echo "find_replace_basename1:"
          echo "${{ steps.find_replace_basename1.outputs.modifiedFiles }}\n"
          echo "find_replace_basename2:"
          echo "${{ steps.find_replace_basename2.outputs.modifiedFiles }}\n"
          echo "find_replace_basename3:"
          echo "${{ steps.find_replace_basename3.outputs.modifiedFiles }}\n"

      - name: 🚀 FTP Deploy to Bluehost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTPDEPLOY_SERVER }}
          username: ${{ secrets.FTPDEPLOY_USERNAME }}
          password: ${{ secrets.FTPDEPLOY_PASSWORD }}
          protocol: ftps
          local-dir: ./dist/

  deploy:
    name: Deploy
    # Deploy only for main branch
    if: github.ref == 'refs/heads/main'
    needs: buildAndTest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Manual deployment
    # See https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now/
    environment:
      name: prod
      url: https://dcpesses.github.io/portfolio-redux/ # <- Change to your site url
    steps:
      # Download dist artifacts
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist/

      - name: Set current date as env variable
        run: echo "NOW=$(TZ=America/Los_Angeles date +'%F %T %Z')" >> $GITHUB_ENV

      # - name: Debug current date
      #   run: echo "${{ env.NOW }}" # Gives "2024-02-16 16:53:32 PST"

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "DATE_TIME"
          replace: "${{ env.NOW }}"
          regex: false
          include: "**index.html"

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
